[package]
name = "koblas"
version = "1.1.2"
edition = "2021"
description = "Lightweight SOCKS5 proxy server"
readme = "README.md"
homepage = "https://github.com/ynuwenhof/koblas"
repository = "https://github.com/ynuwenhof/koblas"
license = "MIT OR Apache-2.0"
keywords = ["proxy", "socks", "server"]

[dependencies]
toml = "0.8.19"
tracing = "0.1.40"
tracing-error = "0.2.0"

[dependencies.argon2]
version = "0.5.3"
features = ["std"]

[dependencies.clap]
version = "4.5.17"
features = ["derive", "env"]

[dependencies.ipnet]
version = "2.10.0"
features = ["serde"]

[dependencies.rand_core]
version = "0.6.4"
features = ["std"]

[dependencies.serde]
version = "1.0.210"
features = ["derive"]

[dependencies.tokio]
version = "1.40.0"
features = ["fs", "net", "io-util", "rt-multi-thread"]

[dependencies.tracing-subscriber]
version = "0.3.18"
features = ["env-filter"]
